apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tazlab-secrets-vault
spec:
  provider:
    vault:
      server: https://lushycorp-vault.magellanic-gondola.ts.net:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-eso-token
          namespace: external-secrets
          key: token
      caSecret:
        name: vault-ca-cert
        key: ca.crt
