apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: vault-ca-cert
    namespace: external-secrets
    files:
      - ca.crt
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
resources:
  - clustersecretstore.yaml
