apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/traefik
  - ./metallb
  - ./longhorn

patches:
  - target:
      kind: HelmRelease
      name: traefik
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: traefik
      spec:
        values:
          service:
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.1.240
          persistence:
            enabled: true
            storageClass: "longhorn"
            size: 128Mi
