apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sa-vso-auth-sa.yaml
  - vault-ca-cert.yaml
  - vaultconnection.yaml
  - vaultauth.yaml
  - helmrelease.yaml
  - sa-vso-auth-sa-tazlab-db.yaml
  - vaultstaticsecret-mnemosyne.yaml
