apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - sa-vso-auth-sa.yaml
  - sa-vso-auth-sa-tazlab-db.yaml
  - sa-vso-auth-sa-auth.yaml
  - sa-vso-auth-sa-cert-manager.yaml
  - sa-vso-auth-sa-cloudflare-ddns.yaml
  - sa-vso-auth-sa-dex.yaml
  - sa-vso-auth-sa-flux-system.yaml
  - sa-vso-auth-sa-longhorn-system.yaml
  - sa-vso-auth-sa-monitoring.yaml
  - sa-vso-auth-sa-hindsight.yaml

  # PKI VaultAuth and VaultPKISecret moved to vso-secrets/kustomization.yaml
