apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-auth-sa
  namespace: hugo-blog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-auth-sa
  namespace: hugo-wiki
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-auth-sa
  namespace: ai-agents
