apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-pki-database-server
  namespace: vso-system
spec:
  allowedNamespaces:
  - tazlab-db
  jwt:
    audiences:
    - https://kubernetes.default.svc.cluster.local
    role: vso-role-database-server
    serviceAccount: vso-auth-sa
    tokenExpirationSeconds: 600
  method: jwt
  mount: jwt
  vaultConnectionRef: hetzner-vault-connection
