apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cloudflare-ddns
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/infra/cloudflare-ddns/CLOUDFLARE_API_TOKEN
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: cloudflare-api-token
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        api-token:
          text: '{{ get .Secrets "value" }}'
  rolloutRestartTargets:
  - kind: Deployment
    name: cloudflare-ddns
