apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-tls
  namespace: auth
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard
  refreshAfter: 3600s
  destination:
    name: wildcard-tls
    create: true
    overwrite: true
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.crt:
          text: '{{ get .Secrets "WILDCARD_CRT" }}'
        tls.key:
          text: '{{ get .Secrets "WILDCARD_KEY" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-tls
  namespace: dex
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard
  refreshAfter: 3600s
  destination:
    name: wildcard-tls
    create: true
    overwrite: true
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.crt:
          text: '{{ get .Secrets "WILDCARD_CRT" }}'
        tls.key:
          text: '{{ get .Secrets "WILDCARD_KEY" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-tls
  namespace: hugo-blog
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard
  refreshAfter: 3600s
  destination:
    name: wildcard-tls
    create: true
    overwrite: true
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.crt:
          text: '{{ get .Secrets "WILDCARD_CRT" }}'
        tls.key:
          text: '{{ get .Secrets "WILDCARD_KEY" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-tls
  namespace: hugo-wiki
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard
  refreshAfter: 3600s
  destination:
    name: wildcard-tls
    create: true
    overwrite: true
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.crt:
          text: '{{ get .Secrets "WILDCARD_CRT" }}'
        tls.key:
          text: '{{ get .Secrets "WILDCARD_KEY" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-tls
  namespace: ai-agents
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard
  refreshAfter: 3600s
  destination:
    name: wildcard-tls
    create: true
    overwrite: true
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.crt:
          text: '{{ get .Secrets "WILDCARD_CRT" }}'
        tls.key:
          text: '{{ get .Secrets "WILDCARD_KEY" }}'
