apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hindsight-mcp-token
  namespace: hindsight
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/apps/hindsight/MCP_AUTH_TOKEN
  refreshAfter: 3600s
  destination:
    create: true
    name: hindsight-mcp-token
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: hindsight-api
