apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vault-pki-tls
  namespace: vso-system
spec:
  vaultAuthRef: vso-pki-ingress
  mount: pki_int
  role: internal-ingress
  commonName: "*.tazlab.net"
  ttl: "168h"
  expiryOffset: "24h"
  removeRootsFromChain: false
  destination:
    create: true
    name: vault-pki-tls
    type: kubernetes.io/tls
    overwrite: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "auth,dex"
