apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-crt-vss
  namespace: vso-system
spec:
  vaultAuthRef: vault-auth-crt
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard/WILDCARD_CRT
  refreshAfter: 3600s
  destination:
    name: wildcard-crt
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.crt:
          text: '{{ get .Secrets "value" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wildcard-key-vss
  namespace: vso-system
spec:
  vaultAuthRef: vault-auth-key
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/tls/wildcard/WILDCARD_KEY
  refreshAfter: 3600s
  destination:
    name: wildcard-key
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        tls.key:
          text: '{{ get .Secrets "value" }}'
