apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-api-token
  namespace: flux-system
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/infra/github/GITHUB_TOKEN
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: github-api-token
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        github_token:
          text: '{{- printf "%s" (get .Secrets "value") -}}'
