apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: aws-backup-secret
  namespace: longhorn-system
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/infra/longhorn/s3-backup-creds
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: aws-backup-secret
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        AWS_ACCESS_KEY_ID:
          text: '{{ get .Secrets "PROXMOX_S3_ACCESS_KEY" }}'
        AWS_ENDPOINTS:
          text: '{{ get .Secrets "PROXMOX_S3_ENDPOINT" }}'
        AWS_SECRET_ACCESS_KEY:
          text: '{{ get .Secrets "PROXMOX_S3_SECRET_KEY" }}'
