apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: s3-backrest-creds
  namespace: tazlab-db
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/storage/tazlab-db/s3-creds
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: s3-backrest-creds
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        s3.conf:
          text: |
            [global]
            repo1-s3-key={{ get .Secrets "AWS_ACCESS_KEY_ID" }}
            repo1-s3-key-secret={{ get .Secrets "AWS_SECRET_ACCESS_KEY" }}
