apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dex-secrets-sync
  namespace: dex
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/auth/dex/merged
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: dex-google-oauth
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        DEX_GOOGLE_CLIENT_ID:
          text: '{{ get .Secrets "DEX_GOOGLE_CLIENT_ID" }}'
        DEX_GOOGLE_CLIENT_SECRET:
          text: '{{ get .Secrets "DEX_GOOGLE_CLIENT_SECRET" }}'
  rolloutRestartTargets:
    kind: Deployment
    name: dex
