apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vault-pki-tls
  namespace: vso-system
spec:
  vaultAuthRef: vso-pki-ingress
  mount: pki_int
  role: internal-ingress
  commonName: "*.tazlab.net"
  ttl: "168h"
  expiryOffset: "24h"
  destination:
    create: true
    name: vault-pki-tls
    type: kubernetes.io/tls
    overwrite: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "auth,dex"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "auth,dex"
    transformation:
      excludeRaw: true
      templates:
        tls.crt:
          text: |
            {{ .Secrets.certificate }}
        tls.key:
          text: |
            {{ .Secrets.private_key }}
        ca.crt:
          text: |
            {{- range $_, $c := .Secrets.ca_chain }}{{ $c }}
            {{ end }}
            -----BEGIN CERTIFICATE-----
            MIIB8jCCAXigAwIBAgIUD5fkLrrSp2swvwib+S9FeySo1OQwCgYIKoZIzj0EAwMw
            KDEmMCQGA1UEAwwdVGF6TGFiIE9mZmxpbmUgUm9vdCBBdXRob3JpdHkwHhcNMjYw
            NjI1MjI1MTM4WhcNNDYwNjIwMjI1MTM4WjAoMSYwJAYDVQQDDB1UYXpMYWIgT2Zm
            bGluZSBSb290IEF1dGhvcml0eTB2MBAGByqGSM49AgEGBSuBBAAiA2IABF581wHk
            2I9epBVSQJK5MjHmbBIOLmnZGQ2aKv0vyrjP2hi2b/MsEpCsnoat+PGO3RgxbEKY
            cNRsmwaPWZBTT3XxhFIaGsXL/YNCcE/UowxdYZLg0AX5UOARdkB7/7VrAaNjMGEw
            DwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFIgNdmR7
            Y9Jdps3TUrCNISQPreEGMB8GA1UdIwQYMBaAFIgNdmR7Y9Jdps3TUrCNISQPreEG
            MAoGCCqGSM49BAMDA2gAMGUCMQDIMVWXD5IHMRKRp6BuJX4Knrdd8IhYsBabjE3t
            hmrQChvCtl8nvWKJREzNGvzrQFACMHj0JEHvZXsNv7/ZtnOv6pJIjVFmh2aLrgRH
            L16szenOUeOaD2iYbfp1K1FIXeCbVw==
            -----END CERTIFICATE-----
