apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/infra/monitoring/ALERTMANAGER_DISCORD_WEBHOOK
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: alertmanager-discord-webhook
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        alertmanager.yaml:
          text: |
            route:
              group_by: ['alertname', 'namespace', 'job']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 4h
              receiver: discord
            receivers:
              - name: discord
                discord_configs:
                  - webhook_url: '{{ get .Secrets "value" }}'
