apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hindsight-gemini-key
  namespace: hindsight
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/apps/hindsight/GEMINI_API_KEY
  refreshAfter: 3600s
  destination:
    create: true
    name: hindsight-gemini-key
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: hindsight-api
    - kind: Deployment
      name: hindsight-worker
