apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy-dex-secret
  namespace: dex
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/auth/oauth2-proxy/merged
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: oauth2-proxy-dex-secret
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        OAUTH2_PROXY_CLIENT_SECRET:
          text: '{{ get .Secrets "OAUTH2_PROXY_CLIENT_SECRET" }}'
