apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: local-jwt-auth
  namespace: auth
spec:
  vaultConnectionRef: vso-system/hetzner-vault-connection
  method: jwt
  mount: jwt
  jwt:
    role: vso-role-jwt
    serviceAccount: vso-auth-sa
    audiences:
      - https://kubernetes.default.svc.cluster.local
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: local-jwt-auth
  namespace: dex
spec:
  vaultConnectionRef: vso-system/hetzner-vault-connection
  method: jwt
  mount: jwt
  jwt:
    role: vso-role-jwt
    serviceAccount: vso-auth-sa
    audiences:
      - https://kubernetes.default.svc.cluster.local
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: local-jwt-auth
  namespace: hugo-blog
spec:
  vaultConnectionRef: vso-system/hetzner-vault-connection
  method: jwt
  mount: jwt
  jwt:
    role: vso-role-jwt
    serviceAccount: vso-auth-sa
    audiences:
      - https://kubernetes.default.svc.cluster.local
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: local-jwt-auth
  namespace: hugo-wiki
spec:
  vaultConnectionRef: vso-system/hetzner-vault-connection
  method: jwt
  mount: jwt
  jwt:
    role: vso-role-jwt
    serviceAccount: vso-auth-sa
    audiences:
      - https://kubernetes.default.svc.cluster.local
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: local-jwt-auth
  namespace: ai-agents
spec:
  vaultConnectionRef: vso-system/hetzner-vault-connection
  method: jwt
  mount: jwt
  jwt:
    role: vso-role-jwt
    serviceAccount: vso-auth-sa
    audiences:
      - https://kubernetes.default.svc.cluster.local
    tokenExpirationSeconds: 600
