apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dex-config-rendered
  namespace: dex
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/auth/dex/merged
  refreshAfter: 3600s
  hmacSecretData: true
  destination:
    create: true
    name: dex-rendered-config
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates:
        config.yaml:
          text: |
            issuer: https://dex.tazlab.net

            storage:
              type: kubernetes
              config:
                inCluster: true

            web:
              http: 0.0.0.0:5556
              allowedOrigins:
                - https://dex.tazlab.net

            grpc:
              addr: 0.0.0.0:5558

            oauth2:
              skipApprovalScreen: true

            connectors:
              - type: google
                id: google
                name: Google
                config:
                  clientID: {{ get .Secrets "DEX_GOOGLE_CLIENT_ID" }}
                  clientSecret: {{ get .Secrets "DEX_GOOGLE_CLIENT_SECRET" }}
                  redirectURI: https://dex.tazlab.net/callback

            staticClients:
              - id: oauth2-proxy
                secretEnv: OAUTH2_PROXY_CLIENT_SECRET
                redirectURIs:
                  - https://auth.tazlab.net/oauth2/callback
                name: oauth2-proxy

            enablePasswordDB: false

            logger:
              level: info
              format: json
