apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mnemosyne-mcp-secrets
  namespace: tazlab-db
spec:
  vaultAuthRef: vso-system/vso-jwt-auth
  mount: secret
  type: kv-v2
  path: tazlab-k8s/static/apps/mnemosyne-mcp/GEMINI_API_KEY
  refreshAfter: 3600s
  destination:
    create: true
    name: mnemosyne-mcp-secrets
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: mnemosyne-mcp
