apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: ai-agents
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets
  target:
    name: openclaw-secrets
    template:
      engineVersion: v2
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: /ephemeral-castle/tazlab-k8s/proxmox
        property: OPENCLAW_GATEWAY_TOKEN
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: /ephemeral-castle/tazlab-k8s/proxmox
        property: TELEGRAM_BOT_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: /ephemeral-castle/tazlab-k8s/proxmox
        property: OPENAI_API_KEY
    - secretKey: ELEVENLABS_API_KEY
      remoteRef:
        key: /ephemeral-castle/tazlab-k8s/proxmox
        property: ELEVENLABS_API_KEY
