apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openclaw-secrets-v2
  namespace: ai-agents
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets
  target:
    name: openclaw-secrets
    template:
      engineVersion: v2
  dataFrom:
  - find:
      path: ""
