apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: ai-agents
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets-vault
  target:
    name: openclaw-secrets
    template:
      engineVersion: v2
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: tazlab-k8s/static/apps/openclaw/OPENCLAW_GATEWAY_TOKEN
        property: value
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: tazlab-k8s/static/apps/openclaw/TELEGRAM_BOT_TOKEN
        property: value
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: tazlab-k8s/static/apps/openclaw/OPENAI_API_KEY
        property: value
    - secretKey: ELEVENLABS_API_KEY
      remoteRef:
        key: tazlab-k8s/static/apps/openclaw/ELEVENLABS_API_KEY
        property: value
