apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets-vault
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: tazlab-k8s/static/auth/oauth2-proxy/OAUTH2_PROXY_CLIENT_SECRET
        property: value
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: tazlab-k8s/static/auth/oauth2-proxy/OAUTH2_PROXY_COOKIE_SECRET
        property: value
