apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: OAUTH2_PROXY_CLIENT_SECRET
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: OAUTH2_PROXY_COOKIE_SECRET
