apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - allowed-emails-configmap.yaml
  - wildcard-tls-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml
