apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:V8A1u5I7BRAlowyt2s8yME6VN9Q=,iv:r++HAzeJPD8wKNOB/kI41pZVfVKcqMU4uRkTPfK0mss=,tag:FPUXn6206+JmikSa5utoPQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xZ4Uc4i65cAWqypQ1QrXeSFDhVQe3K0rTKNeQLFyE+MEBFi1onhhLQ==,iv:KORf/GyGR5TNne2UqrsCTN4EyDe839DB/aEeQ8pjNFo=,tag:FCeg8WaWpP8JIGvDFpVGxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18nppsdntt6frwzus30c6n74fpgr6zwqvhampmr6m8qtzl64v857qg55kg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbmRadW5QUkJpWUVSWEc4
            RnU1QVRJMnFacjY5TDNkV2hDOWo2WXlISXdZCitLMm1meUdJOVkzU25jenlnaVpa
            RHFpR2p4Nks2blBIaFhZeEtZaGJDREkKLS0tIFJnMElBQkpaUlpJV1NsYXNQWEg5
            NHR5UVNnNEFDbjZpZ2tzM25kK2dYMU0K4VeyDzOs1C/grby6bWNQMzQcmSmJOgHM
            jpSlxUWJmKMqF2EzgeEacAvG4GEQ86priii8ECbQgdlTt27leNFCbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T23:08:07Z"
    mac: ENC[AES256_GCM,data:dq/TJaf6Hz0GRe0RBkE2YkK3gbSAl/Wqg2JS8G+UpzdKk5FjP2ygYCzQnLB8tsP6ogj3Wvy/BCXlR+To71Mov7B9ociOArDTm5LZk+RCbmoN7QDshRc6FL0u5cvUV9rvYB6ysaG+WjBJyxvURPW46icUDMwq2P0ekfF18sf/cbA=,iv:7cfPMV4vvyMfRz2RYQ13lz9FuYurOvf7xgkTEDushnE=,tag:FR3mWIK5S1UK6G3NUwRwZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
