apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: networking
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:/js7pB7DxE60jAFAu65kWLYvzjvX2DHK6y22ZHjctpyLaDh/gvPklQ==,iv:Fn/wOigV/2Dzxhk5fQhK0UvFe0iPLjPojTZG9yAXPfI=,tag:xnVxr92+WbXTyoC/O0QZSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18nppsdntt6frwzus30c6n74fpgr6zwqvhampmr6m8qtzl64v857qg55kg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK0ppemc3MXdGZlZiWEcx
            Sk9rcUhxTTYyNEJIeFFDR2k2SHEwV1lwV2xZCkN0aWVpbUc1QzhWNEh6M0orclZj
            UWR5OU5MbytMYy8wMFJvblYzZ1BBeDAKLS0tIHBmYWpadk5Xc2NiaG5ya2tJRlBw
            dDNQU3ozTXlMYm5LZUozZEIrVTBYNjgK9qqzF0e4gpKh60+J6PuNoqmpRbPuBDas
            t+oEm0vLC+LBUfCzLzx8TLvE/9gdUceRU6Pa8UQq9Dga0A/aeaaesg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T01:12:12Z"
    mac: ENC[AES256_GCM,data:WoWwPe44S+vs0JM/07vQnsvFFgvewLXfsCInrRwjMMwCu32TA16XUagCFCHv0bWtA7tI55VaJvWdhAWLeyKBO6NDDDWLbuE0CH55KptYySxe0JrmUvcpICo7+vkq/Kr1NH3rTVHmQ+TRHnZRiA6VScUqVzVQZE3SzMq2306rXSE=,iv:6s0Q23L6uPi1de8gIKmcnmkR731aSES+SCzkHS1LT90=,tag:Qu6EVxQcfNbB9uF9/AOQ5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
