apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-ingress
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.api: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Traefik"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "traefik.png"
spec:
  ingressClassName: tazlab-ingress
  rules:
    - http:
        paths:
          - path: /traefik
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 8080
