apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../vso/vaultconnection.yaml
  - ../vso/vaultauth.yaml
  - ../vso/vaultstaticsecret-mnemosyne.yaml
  - ../vso/vaultstaticsecret-cloudflare-ddns.yaml
  - ../vso/vaultstaticsecret-cert-manager.yaml
  - ../vso/vaultstaticsecret-github-api-token.yaml
  - ../vso/vaultstaticsecret-aws-backup-secret.yaml
  - ../vso/vaultstaticsecret-s3-backrest-creds.yaml
  - ../vso/vaultstaticsecret-dex-secrets-sync.yaml
  - ../vso/vaultstaticsecret-oauth2-proxy-secrets-sync.yaml
  - ../vso/vaultstaticsecret-oauth2-proxy-dex-secret-sync.yaml
  - ../vso/vaultauth-pki-ingress.yaml
  - ../vso/vaultauth-pki-db-mnemosyne.yaml
  - ../vso/vaultauth-pki-db-grafana.yaml
  - ../vso/vaultauth-pki-db-pgadmin.yaml
  - ../vso/vaultauth-pki-db-tazlab-admin.yaml
  - ../vso/vaultauth-pki-replication.yaml
  - ../vso/vaultstaticsecret-alertmanager-discord.yaml
  - ../vso/vaultauth-pki-local-mtls.yaml
  - ../vso/vaultauth-pki-database-server.yaml
  - ../vso/vaultpkisecret-pki-tls.yaml
