github_token: ENC[AES256_GCM,data:ZqfXsn3pBsBr4YOYEiQQIsgEmWwX34FVZG6g/0LR6gXTuOPw7h/Hjg==,iv:+kZzFEwr9xG/eKbhJrgNcnGcyb5DtidGQ9cnEZKOhnI=,tag:aPq9st5K1RcSggrG6c3IRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18nppsdntt6frwzus30c6n74fpgr6zwqvhampmr6m8qtzl64v857qg55kg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTVN6NTZNZjZ5UlZhRFpi
            UXpYNWxJdUZTOU92aStCTGcxaVFmbWUxSFJrCjM4WDV2OFZCTksrZkhuUm9yK0l1
            MXZJL0ludjZtUUNrd1ZqTXJYQ3ZmNnMKLS0tIHhpN0k2S1RET2p3RlpFQXdZZVVI
            dTdGRDJ3VWdjR0dhd3VyZ1lWdkdiancKPpD/zViszMNXfVWmZfTlBUP7Tj/6MW8L
            nzor+JlQwLY/WTJ33CnA/9WWYKEYq/Te6xnvqP87XoVb6l+2G10JXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:12:07Z"
    mac: ENC[AES256_GCM,data:oBWmsEFrvcxJ48YKqyL3ZtaBojKHfKqv1gIMGizBbBPXIFApmQWU2vxpahJmioz4iCJ56KpsO6bi6OK5IUlcvGxS4cGqWZEqIsHTZS6fqPLIIIqZiOKIpOnoGBSj1W4t5QXP5464pqrYf8pVCnupdcYwkmcLfdGdoSzZ+b622iA=,iv:0Mb1SuDvS3Htpi8m8PZiN08NC5ydm3vUxuefUsJoYd8=,tag:tdaIUlamXhdaT74h1iBvGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
