apiVersion: v1
kind: Service
metadata:
  name: longhorn-http
  namespace: longhorn-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
spec:
  type: LoadBalancer
  selector:
    app: longhorn-ui
  ports:
    - port: 8002
      targetPort: 80
