apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
    metallb.universe.tf/allow-shared-ip: "tazlab-internal-dashboard"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Longhorn"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "longhorn.png"
spec:
  type: LoadBalancer
  selector:
    app: longhorn-ui
  ports:
    - port: 8002
      targetPort: 80
