# longhorn-config.yaml (Configurazione Default S3)
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://tazlab-longhorn@eu-central-1/"
  credentialSecret: "aws-backup-secret"
  pollInterval: "300s"