apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cert-manager
  - ../traefik
  - ../monitoring
  - ../postgres-operator
  - ../dex
  - ../auth
  - ../cloudflare-ddns
  - ../tazlab-db
  - ../hugo-blog
