apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: tazlab-db
  namespace: tazlab-db
spec:
  postgresVersion: 16
  databaseInitSQL:
    name: tazlab-db-init-sql
    key: init.sql
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: longhorn-postgres
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: s3-backrest-creds
      repos:
      - name: repo1 # S3 Storage (Immortality)
        s3:
          bucket: "tazlab-longhorn"
          endpoint: "s3.amazonaws.com"
          region: "eu-central-1"
      - name: repo2 # Local Storage (Fast recovery)
        volume:
          volumeClaimSpec:
            storageClassName: longhorn-postgres
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  proxy:
    pgBouncer:
      replicas: 1
  users:
    - name: mnemosyne
      databases:
        - tazlab_memory
    - name: tazlab-admin
      databases:
        - tazlab_test
