apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets
  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: TAILSCALE_OPERATOR_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: TAILSCALE_OPERATOR_CLIENT_SECRET
