apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets-vault
  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: tazlab-k8s/static/infra/tailscale/TAILSCALE_OPERATOR_CLIENT_ID
        property: value
    - secretKey: clientSecret
      remoteRef:
        key: tazlab-k8s/static/infra/tailscale/TAILSCALE_OPERATOR_CLIENT_SECRET
        property: value
