apiVersion: v1
kind: Service
metadata:
  name: tailscale-apiserver
  namespace: kube-system
  annotations:
    tailscale.com/hostname: lushycorp-k8s
    tailscale.com/tags: tag:k8s
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    component: kube-apiserver
    tier: control-plane
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
