apiVersion: v1
kind: Service
metadata:
  name: nameserver-static
  namespace: tailscale
spec:
  type: ClusterIP
  clusterIP: 10.96.0.101
  selector:
    app: nameserver
  ports:
  - name: udp
    port: 53
    protocol: UDP
    targetPort: 1053
  - name: tcp
    port: 53
    protocol: TCP
    targetPort: 1053
