apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-dns-relay
  namespace: tailscale
data:
  Corefile: |
    .:5353 {
        hosts {
            100.82.13.87 lushycorp-vault.magellanic-gondola.ts.net
            fallthrough
        }
        forward . 1.1.1.1 8.8.8.8
    }
