apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale-dns-relay
  namespace: tailscale
spec:
  selector:
    matchLabels:
      app: tailscale-dns-relay
  template:
    metadata:
      labels:
        app: tailscale-dns-relay
    spec:
      hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 100.100.100.100
      tolerations:
        - operator: Exists
      containers:
        - name: coredns
          image: registry.k8s.io/coredns/coredns:v1.13.2
          args: ["-conf", "/etc/coredns/Corefile"]
          volumeMounts:
            - name: corefile
              mountPath: /etc/coredns
      volumes:
        - name: corefile
          configMap:
            name: tailscale-dns-relay
