apiVersion: v1
kind: Service
metadata:
  name: tailscale-dns-relay
  namespace: tailscale
spec:
  clusterIP: 10.96.0.101
  selector:
    app: tailscale-dns-relay
  ports:
    - protocol: UDP
      port: 53
      targetPort: 5353
