apiVersion: v1
kind: Service
metadata:
  name: tailscale-dns-static
  namespace: tailscale
spec:
  clusterIP: 10.96.0.100
  selector:
    app: tailscale-dns
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
