apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnemosyne-mcp
  namespace: tazlab-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnemosyne-mcp
  template:
    metadata:
      labels:
        app: mnemosyne-mcp
    spec:
      containers:
        - name: server
          image: tazzo/mnemosyne-mcp:mcp-13-61c6c8f5d17362d2275766068f1c21b8e3eea013 # {"$imagepolicy": "flux-system:mnemosyne-mcp"}
                  env:
                  - name: MCP_TRANSPORT
                    value: "sse"
                  - name: DB_HOST
          
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: password
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mnemosyne-mcp-secrets
                  key: GEMINI_API_KEY
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
