apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnemosyne-mcp
  namespace: tazlab-db
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnemosyne-mcp
  template:
    metadata:
      labels:
        app: mnemosyne-mcp
    spec:
      serviceAccountName: mnemosyne-mcp-sa
      containers:
        - name: server
          image: tazzo/mnemosyne-mcp:mcp-43-f8a28f062b2dce8e8a82f33d4447c4547d0fca0b # {"$imagepolicy": "flux-system:mnemosyne-mcp"}
          imagePullPolicy: Always
          env:
            - name: MCP_TRANSPORT
              value: "http"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-mnemosyne
                  key: password
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mnemosyne-mcp-secrets
                  key: value
            - name: DB_SSLMODE
              value: "verify-full"
            - name: DB_SSLCERT
              value: "/etc/secrets/tls/tls.crt"
            - name: DB_SSLKEY
              value: "/etc/secrets/tls/tls.key"
            - name: DB_SSLROOTCERT
              value: "/etc/secrets/tls/ca.crt"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi

          volumeMounts:
            - name: tls-certs
              mountPath: /etc/secrets/tls
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: db-client-mnemosyne-tls
            defaultMode: 384