apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mnemosyne-mcp-secrets
  namespace: tazlab-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-tazlab
    kind: ClusterSecretStore
  target:
    name: mnemosyne-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: /ephemeral-castle/tazlab-k8s/mnemosyne-mcp
        property: GEMINI_API_KEY
