apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mnemosyne-mcp-secrets
  namespace: tazlab-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tazlab-secrets-vault
    kind: ClusterSecretStore
  target:
    name: mnemosyne-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: tazlab-k8s/static/apps/mnemosyne-mcp/GEMINI_API_KEY
        property: value
