apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-google-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets-vault
  target:
    name: dex-google-secrets
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: tazlab-k8s/static/auth/dex/DEX_GOOGLE_CLIENT_ID
        property: value
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: tazlab-k8s/static/auth/dex/DEX_GOOGLE_CLIENT_SECRET
        property: value
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: tazlab-k8s/static/auth/oauth2-proxy/OAUTH2_PROXY_CLIENT_SECRET
        property: value
