apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-google-oauth
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets-vault
  target:
    name: dex-google-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DEX_GOOGLE_CLIENT_ID: "{{ .DEX_GOOGLE_CLIENT_ID }}"
        DEX_GOOGLE_CLIENT_SECRET: "{{ .DEX_GOOGLE_CLIENT_SECRET }}"
  data:
    - secretKey: DEX_GOOGLE_CLIENT_ID
      remoteRef:
        key: tazlab-k8s/static/auth/dex/DEX_GOOGLE_CLIENT_ID
        property: value
    - secretKey: DEX_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: tazlab-k8s/static/auth/dex/DEX_GOOGLE_CLIENT_SECRET
        property: value
