apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-api-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tazlab-secrets
  target:
    name: github-api-token
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: GITHUB_TOKEN
