apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw
  namespace: ai-agents
  labels:
    app: openclaw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openclaw
  template:
    metadata:
      labels:
        app: openclaw
    spec:
      serviceAccountName: openclaw-sa
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: openclaw
          image: tazzo/openclaw-custom:openclaw-4-0c9df4baadf4f5853281e68f7752cca534b66c96 # {"$imagepolicy": "flux-system:openclaw"}
          command: ["node", "dist/index.js", "gateway", "--bind", "lan", "--port", "18789", "--allow-unconfigured"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 18789
              name: gateway
          env:
            - name: OPENCLAW_GATEWAY_PORT
              value: "18789"
            - name: OPENCLAW_GATEWAY_BIND
              value: "lan"
            - name: OPENCLAW_GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openclaw-secrets
                  key: OPENCLAW_GATEWAY_TOKEN
            - name: OPENCLAW_GATEWAY_CONTROLUI_DANGEROUSLYALLOWHOSTHEADERORIGINFALLBACK
              value: "true"
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openclaw-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openclaw-secrets
                  key: OPENAI_API_KEY
            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openclaw-secrets
                  key: ELEVENLABS_API_KEY
          volumeMounts:
            - name: config
              mountPath: /home/node/.openclaw
            - name: workspace
              mountPath: /home/node/workspace
          resources:
            limits:
              cpu: "1.0"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: openclaw-config
        - name: workspace
          persistentVolumeClaim:
            claimName: openclaw-workspace
