apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw
  namespace: ai-agents
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: openclaw.tazlab.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openclaw
                port:
                  number: 18789
  tls:
    - hosts:
        - openclaw.tazlab.net
      secretName: wildcard-tls
