apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-config
  namespace: ai-agents
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tazlab-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-workspace
  namespace: ai-agents
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tazlab-storage
  resources:
    requests:
      storage: 10Gi
