apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/emberstack/helm-charts/reflector
  ref:
    tag: 10.0.45
