apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: tazlab-db
  namespace: tazlab-db
spec:
  postgresVersion: 16
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - secret:
            name: s3-backrest-creds
      repo:
        name: repo1
        s3:
          bucket: "tazlab-storage"
          endpoint: "s3.amazonaws.com"
          region: "eu-central-1"
      options:
        - --delta
  databaseInitSQL:
    name: tazlab-db-init-sql
    key: init.sql
  instances:
    - name: instance1
      replicas: 1
      metadata:
        labels:
          app.kubernetes.io/name: tazlab-db
      dataVolumeClaimSpec:
        storageClassName: tazlab-storage
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
  backups:
    pgbackrest:
      global:
        repo1-path: /pgbackrest/repo1
        repo1-type: s3
      configuration:
        - secret:
            name: s3-backrest-creds
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 1-6"
        s3:
          bucket: "tazlab-storage"
          endpoint: "s3.amazonaws.com"
          region: "eu-central-1"
  proxy:
    pgBouncer:
      replicas: 1
  users:
    - name: pgadmin
      databases:
        - postgres
    - name: mnemosyne
      databases:
        - mnemosyne
    - name: tazlab-admin
      databases:
        - tazlab
        - tazlab-test
    - name: grafana
      databases:
        - grafana
  customTLSSecret:
    name: tazlab-db-server-tls
    items:
      - key: ca.crt
        path: ca.crt
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
  customReplicationTLSSecret:
    name: tazlab-db-server-tls
    items:
      - key: ca.crt
        path: ca.crt
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - hostssl grafana grafana 0.0.0.0/0 cert
          - hostssl grafana grafana ::/0 cert
          - hostssl grafana grafana 0.0.0.0/0 md5
          - hostssl grafana grafana ::/0 md5
          - hostssl all grafana 0.0.0.0/0 md5
          - hostssl all grafana ::/0 md5
          - host grafana grafana 0.0.0.0/0 md5
          - host grafana grafana ::/0 md5
          - host all grafana 0.0.0.0/0 md5
          - host all grafana ::/0 md5
          - hostssl mnemosyne mnemosyne 0.0.0.0/0 cert
          - hostssl mnemosyne mnemosyne ::/0 cert
          - host tazlab-admin all 0.0.0.0/0 md5
          - host tazlab-admin all ::/0 md5
          - hostssl postgres pgadmin 0.0.0.0/0 cert
          - hostssl postgres pgadmin ::/0 cert
          - host postgres pgadmin 0.0.0.0/0 reject
          - host postgres pgadmin ::/0 reject
          - host all all 10.0.0.0/8 md5
          - host all all 10.244.0.0/16 md5
