apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: tazlab-db
  namespace: tazlab-db
spec:
  postgresVersion: 16
  # Riattiviamo il restore automatico (Point-In-Time)
  dataSource:
    pgbackrest:
      stanza: db
      repo:
        name: repo1
      options:
        - --type=immediate
        - --delta
  databaseInitSQL:
    name: tazlab-db-init-sql
    key: init.sql
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: tazlab-storage
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
        # Il percorso deve essere vuoto per usare la root del bucket dove abbiamo spostato i dati
        repo1-path: / 
      configuration:
        - secret:
            name: s3-backrest-creds
      repos:
      - name: repo1 # S3 Storage (Immortality)
        s3:
          bucket: "tazlab-longhorn"
          endpoint: "s3.amazonaws.com"
          region: "eu-central-1"
  proxy:
    pgBouncer:
      replicas: 1
  users:
    - name: mnemosyne
      databases:
        - mnemosyne
    - name: tazlab-admin
      databases:
        - tazlab
        - tazlab-test
