apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - init-sql.yaml
  - tailnet-service.yaml  - vaultpkisecret-server-tls.yaml
  - vaultpkisecret-client-mnemosyne.yaml
  - vaultpkisecret-client-pgadmin.yaml
  - vaultpkisecret-client-tazlab-admin.yaml
