apiVersion: v1
kind: Service
metadata:
  name: tazlab-db-tailnet
  namespace: tazlab-db
  annotations:
    tailscale.com/hostname: "tazlab-db"
    tailscale.com/tags: "tag:k8s"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    postgres-operator.crunchydata.com/cluster: tazlab-db
    postgres-operator.crunchydata.com/role: master
