apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: db-client-pgadmin-tls
  namespace: tazlab-db
spec:
  vaultAuthRef: vso-system/vso-pki-db-pgadmin
  mount: pki_int
  role: db-client-pgadmin
  commonName: pgadmin
  ttl: "24h"
  expiryOffset: "4h"
  destination:
    create: true
    name: db-client-pgadmin-tls
    type: kubernetes.io/tls
    overwrite: true

    transformation:
      excludeRaw: true
      templates:
        tls.crt:
          text: |
            {{ .Secrets.certificate }}
        tls.key:
          text: |
            {{ .Secrets.private_key }}
        ca.crt:
          text: |
            {{- range $_, $c := .Secrets.ca_chain }}{{ $c }}
            {{ end }}
            -----BEGIN CERTIFICATE-----
            MIIB8jCCAXigAwIBAgIUD5fkLrrSp2swvwib+S9FeySo1OQwCgYIKoZIzj0EAwMw
            KDEmMCQGA1UEAwwdVGF6TGFiIE9mZmxpbmUgUm9vdCBBdXRob3JpdHkwHhcNMjYw
            NjI1MjI1MTM4WhcNNDYwNjIwMjI1MTM4WjAoMSYwJAYDVQQDDB1UYXpMYWIgT2Zm
            bGluZSBSb290IEF1dGhvcml0eTB2MBAGByqGSM49AgEGBSuBBAAiA2IABF581wHk
            2I9epBVSQJK5MjHmbBIOLmnZGQ2aKv0vyrjP2hi2b/MsEpCsnoat+PGO3RgxbEKY
            cNRsmwaPWZBTT3XxhFIaGsXL/YNCcE/UowxdYZLg0AX5UOARdkB7/7VrAaNjMGEw
            DwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFIgNdmR7
            Y9Jdps3TUrCNISQPreEGMB8GA1UdIwQYMBaAFIgNdmR7Y9Jdps3TUrCNISQPreEG
            MAoGCCqGSM49BAMDA2gAMGUCMQDIMVWXD5IHMRKRp6BuJX4Knrdd8IhYsBabjE3t
            hmrQChvCtl8nvWKJREzNGvzrQFACMHj0JEHvZXsNv7/ZtnOv6pJIjVFmh2aLrgRH
            L16szenOUeOaD2iYbfp1K1FIXeCbVw==
            -----END CERTIFICATE-----