apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: tazlab-db-server-tls
  namespace: tazlab-db
spec:
  vaultAuthRef: vso-system/vso-pki-database-server
  mount: pki_int
  role: database-server
  commonName: tazlab-db-primary.tazlab-db.svc
  ttl: "720h"
  expiryOffset: "168h"
  destination:
    create: true
    name: tazlab-db-server-tls
    type: kubernetes.io/tls
    overwrite: true
