apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-password-source
  namespace: tazlab-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tazlab-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-password-source
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: GRAFANA_DB_PASSWORD
    - secretKey: user
      remoteRef:
        key: GRAFANA_DB_USER
    - secretKey: dbname
      remoteRef:
        key: GRAFANA_DB_NAME
    - secretKey: host
      remoteRef:
        key: GRAFANA_DB_HOST
