apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sync-grafana-password
  namespace: tazlab-db
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    name: tazlab-secrets
    kind: ClusterSecretStore
  selector:
    secret:
      name: tazlab-db-pguser-grafana
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: GRAFANA_DB_PASSWORD
