apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-backrest-creds
  namespace: tazlab-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-tazlab
  target:
    name: s3-backrest-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # L'operatore si aspetta 'key' e 'key-secret' per i repo s3 nativi
        key: "{{ .AWS_ACCESS_KEY_ID }}"
        key-secret: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
