apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-backrest-creds
  namespace: tazlab-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-tazlab
  target:
    name: s3-backrest-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # File di config che pgBackRest caricherà AUTOMATICAMENTE
        pgbackrest.conf: |
          [global]
          repo1-type=s3
          repo1-s3-key={{ .AWS_ACCESS_KEY_ID }}
          repo1-s3-key-secret={{ .AWS_SECRET_ACCESS_KEY }}
          repo1-s3-bucket=tazlab-longhorn
          repo1-s3-endpoint=s3.amazonaws.com
          repo1-s3-region=eu-central-1
          repo1-path=/pgbackrest/repo1
        # Compatibilità
        repo1-s3-key: "{{ .AWS_ACCESS_KEY_ID }}"
        repo1-s3-key-secret: "{{ .AWS_SECRET_ACCESS_KEY }}"
        key: "{{ .AWS_ACCESS_KEY_ID }}"
        key-secret: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY