apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pgadmin.yaml
  - rbac.yaml
  - tailnet-ingress.yaml
  - servers-configmap.yaml

patches:
  - path: ../../common/wait-for-db-patch.yaml
    target:
      kind: Deployment
      name: pgadmin
