apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: tazlab-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tazlab-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: tazlab-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      serviceAccountName: pgadmin-sa
      initContainers:
        - name: wait-for-db-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get secret tazlab-db-pguser-pgadmin; do
                echo "waiting for database user secret..."
                sleep 5
              done
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:9.12
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@pgadmin.tazlab.net"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tazlab-db-pguser-pgadmin
                  key: password
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
          ports:
            - containerPort: 80
              name: http
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: tazlab-db
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
    metallb.universe.tf/allow-shared-ip: "tazlab-internal-dashboard"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "pgAdmin"
    gethomepage.dev/group: "Management"
    gethomepage.dev/icon: "postgresql.png"
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
    - port: 8001
      targetPort: 80
