apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-bootstrap-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tazlab-secrets-vault
    kind: ClusterSecretStore
  target:
    name: grafana-bootstrap-secret
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_DB_PASSWORD
      remoteRef:
        key: tazlab-k8s/static/monitoring/grafana/GRAFANA_DB_PASSWORD
        property: value
