apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 61.3.1
  releaseName: kube-prometheus-stack
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: grafana-dynamic-creds
      targetPath: grafana.podAnnotations.vault-dynamic-username
      valuesKey: username
  values:
    grafana:
      adminPassword: change-me
      forceDeployDashboards: true
      sidecar:
        dashboards:
          searchNamespace: ALL
        datasources:
          defaultDatasourceEnabled: false
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      serviceAccount:
        create: false
        name: grafana-sa
      containerSecurityContext:
        runAsUser: 472
        runAsGroup: 472
      extraEnvVars:
        - name: GODEBUG
          value: tlskyber=0
      database:
        type: sqlite3
      assertNoLeakedSecrets: false
      grafana.ini:
        server:
          domain: grafana.tazlab.net
          root_url: https://grafana.tazlab.net/
          serve_from_sub_path: false
        auth.proxy:
          enabled: true
          header_name: X-Auth-Request-Email
          header_property: email
          auto_sign_up: true
          enable_login_token: false
          header_email: X-Auth-Request-Email
          sign_up_url: https://dex.tazlab.net/signup
          whitelist: ""
        auth.basic:
          enabled: false
        auth.generic_oauth:
          enabled: true
          name: Dex
          icon: sign-in
          client_id: grafana
          scopes: openid profile email groups
          auth_url: https://dex.tazlab.net/auth
          token_url: https://dex.tazlab.net/token
          api_url: https://dex.tazlab.net/userinfo
          allowed_domains: ""
          allow_sign_up: true
          role_attribute_path: contains(groups[*], 'tazlab-admin') && 'Admin' || 'Viewer'
        auth.anonymous:
          enabled: false
        auth.google:
          enabled: false
        auth.grafana_com:
          enabled: false
        auth.saml:
          enabled: false
        disable_login_form: true
        database:
          type: postgres
          host: tazlab-db-primary.tazlab-db.svc:5432
          name: grafana
          user: grafana
          ssl_mode: verify-full
          ca_cert_path: /etc/grafana/certs/ca.crt
          client_cert_path: /etc/grafana/certs/tls.crt
          client_key_path: /etc/grafana/certs/tls.key
      extraSecretMounts:
        - name: grafana-db-certs
          mountPath: /tmp/db-certs-in
          secretName: db-client-grafana-tls
          readOnly: true
          defaultMode: 384
      extraInitContainers:
        - name: copy-db-certs
          image: alpine:3.21
          command:
            - sh
            - -c
            - cp -rL /tmp/db-certs-in/* /etc/grafana/certs/
              chmod 600 /etc/grafana/certs/tls.key
              ls -la /etc/grafana/certs/
          volumeMounts:
            - name: grafana-db-certs
              readOnly: true
              mountPath: /tmp/db-certs-in
            - name: grafana-certs-empty
              mountPath: /etc/grafana/certs
      extraEmptyDirMounts:
        - name: grafana-certs-empty
          mountPath: /etc/grafana/certs
