apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: false
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    prometheus:
      prometheusSpec:
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: tazlab-storage
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    grafana:
      enabled: true
      serviceAccount:
        create: false
        name: grafana-sa
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
      podAnnotations: {}
      extraSecretMounts:
        - name: grafana-db-creds-mount
          secretName: grafana-dynamic-creds
          mountPath: /etc/secrets/grafana-dynamic-creds
          defaultMode: 0440
          readOnly: true
      grafana.ini:
        server:
          domain: grafana.tazlab.net
          root_url: https://grafana.tazlab.net/
          serve_from_sub_path: false
        database:
          type: postgres
          host: tazlab-db-primary.tazlab-db.svc.cluster.local:5432
          name: grafana
          ssl_mode: disable
        auth.proxy:
          enabled: true
          header_name: X-Auth-Request-Email
          header_property: email
          header_email: X-Auth-Request-Email
          auto_sign_up: true
          sync_ttl: 0
          sync_ttl_api_key: 0
          enable_login_token_rotation: false
          skip_org_role_sync: true
          disable_login_form: true
        security:
          admin_user: ''
          allow_login_without_configured_admin: true
      env:
        GF_DATABASE_USER__FILE: "/etc/secrets/grafana-dynamic-creds/username"
        GF_DATABASE_PASSWORD__FILE: "/etc/secrets/grafana-dynamic-creds/password"
      persistence:
        enabled: false
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.1.240"
          metallb.universe.tf/allow-shared-ip: "tazlab-internal-dashboard"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Grafana"
          gethomepage.dev/group: "Management"
          gethomepage.dev/icon: "grafana.png"
        port: 8005
        targetPort: 3000
