apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - namespace.yaml
  - metrics-server.yaml
  - tailnet-ingress.yaml
  - dashboards/cluster-health.yaml
  - dashboards/nodes-pro.yaml
  - grafana-db-creds.yaml