apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    # Minimal Setup to avoid timeouts
    alertmanager:
      enabled: false
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    
    # Prometheus Configuration
    prometheus:
      prometheusSpec:
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: tazlab-storage
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    
    # Grafana Configuration (Enterprise Postgres Backend)
    grafana:
      enabled: true
      grafana.ini:
        database:
          type: postgres
          host: tazlab-db-primary.tazlab-db.svc.cluster.local:5432
          name: grafana
          user: grafana
        auth.proxy:
          enabled: true
          header_name: X-Auth-Request-User
          header_property: username
          auto_sign_up: true
          sync_ttl: 60
        security:
          admin_user: admin
          disable_login_form: false
        auth:
          oauth_auto_login: false
          disable_login_form: false
      # Environment variables for absolute certainty
      env:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: tazlab-db-primary.tazlab-db.svc.cluster.local:5432
        GF_DATABASE_NAME: grafana
        GF_DATABASE_USER: grafana
      envValueFrom:
        GF_DATABASE_PASSWORD:
          secretKeyRef:
            name: tazlab-db-pguser-grafana
            key: password
      
      persistence:
        enabled: false
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.1.240"
          metallb.universe.tf/allow-shared-ip: "tazlab-internal-dashboard"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Grafana"
          gethomepage.dev/group: "Management"
          gethomepage.dev/icon: "grafana.png"
        port: 8005
        targetPort: 3000
