apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.3.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    # Minimal Setup to avoid timeouts
    alertmanager:
      enabled: false
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    
    # Prometheus Minimal
    prometheus:
      prometheusSpec:
        retention: 1d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: tazlab-storage
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
    
    # Grafana Minimal (SQLite for now)
    grafana:
      enabled: true
      persistence:
        enabled: false
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.1.240"
          metallb.universe.tf/allow-shared-ip: "tazlab-internal-dashboard"
        port: 8005
        targetPort: 3000
