apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tazlab-db-pguser-grafana
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tazlab-secrets-vault
    kind: ClusterSecretStore
  target:
    name: tazlab-db-pguser-grafana
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: tazlab-k8s/static/monitoring/grafana/GRAFANA_DB_PASSWORD
        property: value
    - secretKey: user
      remoteRef:
        key: tazlab-k8s/static/monitoring/grafana/GRAFANA_DB_USER
        property: value
