apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: db-client-grafana-tls
  namespace: monitoring
spec:
  vaultAuthRef: vso-system/vso-pki-db-grafana
  mount: pki_int
  role: db-client-grafana
  commonName: grafana
  ttl: "24h"
  expiryOffset: "4h"
  destination:
    create: true
    name: db-client-grafana-tls
    type: kubernetes.io/tls
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        tls.crt:
          text: |
            {{ .Secrets.certificate }}
        tls.key:
          text: |
            {{ .Secrets.private_key }}
        ca.crt:
          text: |
            {{- range $_, $c := .Secrets.ca_chain }}{{ $c }}
            {{ end -}}