apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-${domain}-tls
  namespace: hugo-blog
spec:
  secretName: blog-${domain}-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  # Allineato al certificato Wildcard del Vault
  commonName: ${domain}
  dnsNames:
    - ${domain}
    - "*.${domain}"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 2048
