apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-blog
  namespace: hugo-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo-blog
  template:
    metadata:
      labels:
        app: hugo-blog
        app.kubernetes.io/name: hugo-blog
    spec:
      containers:
        - name: blog
          image: tazzo/tazlab-blog:blog-58-839e38a72af601e2887cec63ff8c3409ced7a5a1 # {"$imagepolicy": "flux-system:hugo-blog"}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hugo-blog
  namespace: hugo-blog
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hugo-blog
---
# MAIN INGRESS (No redirect)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugo-blog-ingress
  namespace: hugo-blog
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Blog"
    gethomepage.dev/group: "Developer"
    gethomepage.dev/icon: "hugo.png"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - blog.tazlab.net
      secretName: wildcard-tls
  rules:
    - host: blog.tazlab.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hugo-blog
                port:
                  number: 80
---
# REDIRECT INGRESS (With middleware)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hugo-blog-redirect-ingress
  namespace: hugo-blog
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: hugo-blog-hugo-blog-redirect-to-blog@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tazlab.net
        - www.tazlab.net
        - lab.tazlab.net
      secretName: wildcard-tls
  rules:
    - host: lab.tazlab.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hugo-blog
                port:
                  number: 80
    - host: tazlab.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hugo-blog
                port:
                  number: 80
    - host: www.tazlab.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hugo-blog
                port:
                  number: 80
