apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-blog
  namespace: hugo-blog
spec:
  redirectRegex:
    regex: "^https?://(?:www\\.)?tazlab\\.net/(.*)"
    replacement: "https://blog.tazlab.net/${1}"
    permanent: true
