cluster:
    ca:
        crt: ENC[AES256_GCM,data:dG8KH64co110slxeJkrHgQgZ84r30mb4HytMVQjzkEtwpMek1WSeliHjprPj43GhqLOcPtkx8vDmYBkYUHVbYIkMP4kzqG9mK2oncnmXNq7RL8ubTl0zrhkWQbsHdNBlbGJKYR6FiA9tdVAfYZzfUa8KEpS5XBn+3dciFfTIDg0jucNUk2Hn4jBOoLMbcWNkUKuBv7ysJjx30fCMePeTW3CuafiMF+KJdsWem9xuKr98lHGWzzU+pIoxh+ATjnAPdW1PtZwcb+tMoQfiKSTKWch7WcWID9/Lpyl5z9Eco1EY296gYw4o60yRKXpKPDYEkIKgah3HPxHShBwH4YQAqAR2VygVdHDN/NSTDFMS/84dL0llxI3oVbahRgv/pi/32BI1NPNiHy44Oum5wSoQxnzxFvrGKDm9ktnHZIydogVwxWmcTwz1iZZtXjOtFXDySCnCo/R62DT5YAtgkqrl+kC+aB3t/Nim5K0JMx2h39xhoWi312JJffEswWmVsCzELB05kRh+m3dvwvrz2E69Lws4tzrPtdUmqqCH6wIs06P4HFLefAb7KqOusLMtSkZeDBDO1j06itKXbxToeZDgJR9jFi90zXvJcC49AMfeilrh5PLGMpm8s0guIdbJH3PfOlM8qJnNNkPjU0cpIn0I4+eLlUoBODj3wGrVa6Yofk60iTxVAXQ9k2r0h/twcdHKVUBjVwcr438Xrs/i105/1a7C/Ca3Ta4bJvo01prUMtAdptc8kmgh5JMDYaD1e4kx3ujy3mG9NJhncOE3j2RqPy2mm1Cs3ZlpHqM+nwHGaf+yAAB/WKy/hdEbXUk2CEe0V+YuZ1swJjGIYpdVu8k7lUfkFytkT15qVz1mx3mf50/SYyY1craTNvoXSjoPK2gpyBzpWmFiuhMQQdUjtZFo3J34B0R9G0n/3PmRD9s9DQXX5NZuU3C3V3xF0rIB3PzUih2taXm9ndnDx2CrScJyObpu1ef3IPTE2TUOijQMRjTDhWWh+X0t4vpXrtXxThRWl+Nsyg4XfiJXmHw+28ZwLPo7wCbarN7emhg82g==,iv:d0Py0Fm18uLJC61mNq1w6Mx9q0rx0ORKyVZIZuoulBA=,tag:iQHSQf3vX5FftqM4VLyHdA==,type:str]
        key: ""
    clusterName: ENC[AES256_GCM,data:Y2xiZd1sNDRTQdJUT/i2eX4kmNO5,iv:mLM9r3r2A0SKQwZWIMju4UJB0cb8/cZyxyDiLqfcri4=,tag:O4I2hq17jIlIjKdzckNT9A==,type:str]
    controlPlane:
        endpoint: ENC[AES256_GCM,data:9NPDCvNG7IN02bEOD3j6gQQabvq6UK/MOWY=,iv:cQVp3XcK/+Hgn5lWi5nxkmN8Qjp5oTTDvJx1uwE3Kw0=,tag:miGjYOY4up/qOg0bAywn4g==,type:str]
    discovery:
        enabled: ENC[AES256_GCM,data:K0VlHQ==,iv:MZ2w2UhiD73T5j/oSjw6Ktg7A5Ay/+dlGuEeWy93oKE=,tag:nKycpU2CaZMppe2Z1S3aYA==,type:bool]
        registries:
            kubernetes:
                disabled: ENC[AES256_GCM,data:kX0BeA==,iv:1BqAV/70OyXcHUGL4NJHPy0+oIbyQQ2w/0vONxQIapI=,tag:EQp6evOp/GHouI1NewYoKA==,type:bool]
            service: {}
    id: ENC[AES256_GCM,data:f+CwrHcZjMB1u1VSxs9BDv1YmPhqeEIEy8hM/LcXRdw8wHfuFvSTqlGmVoQ=,iv:TIrWNlyWfpQxClBkxbyVdCfkEyTOg9m/Joq8fn19f70=,tag:Bv4clwAmtfXyg+S+x2k+zg==,type:str]
    network:
        dnsDomain: ENC[AES256_GCM,data:WuwsAC1P/KX18oTIDA==,iv:NkBROeT170e5ydQAYj3Y0YjwAGOYe6J2dpzAvy/kXes=,tag:DhiRvdqNH1UNA3eYBzaMWw==,type:str]
        podSubnets:
            - ENC[AES256_GCM,data:+BcS8Dn+zhaEESKJ4A==,iv:M3CXoqPgiIWN8g5FoAfa+b3wP9aa2djrSvAZC5473Q8=,tag:jiSMWripL++z9GdqAua1Pw==,type:str]
        serviceSubnets:
            - ENC[AES256_GCM,data:DSJh4/M5xxucXkBg,iv:6H3rcvYd0aXY47hD0iLPhvWfvh1QGG2AOjcdy5v7MTI=,tag:iHnv2ZgNIPrABOqAd5cupQ==,type:str]
    secret: ENC[AES256_GCM,data:oti+6ijWVqLTxHhfJNXm2rmqQO4V3fHYVlEBOLIfuNV6XJEIv1bgnm8UH6M=,iv:ShaRJ0IGdtS4gjDkZ4mTKLncc8AeLX6Luin6Xrn+j8U=,tag:B+4mq4jF0YuA3uSVeL0p1A==,type:str]
    token: ENC[AES256_GCM,data:/UYo8+l/kevjet7SXvREUSNuZwHrQFA=,iv:geOdNUhaNa6HEc9+e3YtuySQEgLlb1IRYlSDoaNoFt4=,tag:j1l1vb+XG6QwqzRa1PQVGw==,type:str]
debug: ENC[AES256_GCM,data:l1NOPpU=,iv:OV8Ma5IneP2hD9PGP0CI69D5Iy4eCHQwGCW1Zmzwabw=,tag:sOZA1uDau0eLOOwuTdlT/Q==,type:bool]
machine:
    ca:
        crt: ENC[AES256_GCM,data:2De98YRVViPKI5qqzFWGCcP/SnDH+IMORyY0G15m65PRWmXcH8gm+omhVJH9cJpZZs0hAwZbYuBXeVXv4tEy7N0fWTwiQ3vx2xUS5I41UmPH1WFqCTeLgqZneXnRXVCrHW/kS7qFEGOZKgn6mUTglH+vnXy6cZCbJwxKXnbAg147Fw9uuKgyYNK8zCnRY0YMc+0FQH/X0HNByg0rp9GTnLRikm1HWDLZDRJ3sxXIvBrImcFudVqiehix8ewgkxhT5QFK5XdJWdLU2FATC+m9/511H/VIgpy4lxwtN/oNBessZYyQ78jxbdjoHLWPJ4U/9lkLt4IiBJ+I6P8bNb6aGL2Rxs5raEmlDVukLgszC7TRs4u/5dRRiNc67fq/lfm3wm6w8WZquskuDDDwKBcf6Yyl+R8wDtbCsyeo7V4SpSUG6R9GcZ1QxC6Wxew+AU7Ij4K+spUKCYWEYpZg/foj6u1ybzdI5TBBZWYpBk8LLW18TqDWaWW3yC9GItpJTQZHNmvbIHaULxvXo6Yr9Xf7EtfjAqJZoWoBMyVVO/Dse9yeJxOHumzZG8Aqn1LqhwNL1gPpbh0fcEEgwimQ9e6IxQmLdnY0xLVvxn2hqSZ2fF33PS5Y2isCUi4SKabORMpDINsUEyaAS1gjnsRon9fKqxcCnoHg5ntutuVWyeCSpq4fUoOy9wD8YLlXSAnOJ+o9D/l8imec+64tlk8xuvva+Wz8JaIFgyMCvLYvWsfYFC4iX/mnTQg4AIBXAN+W8i421KEF0V1F4wni23L9qcI4K5Wc3F92QBL9hniIfHfVPeoAiKHyHrQ5b+77gSWETlkVDPpzBSDgbZthS0NbngDVLxb0mnfnZUWrOfnkLL+Tndn9hp1w,iv:7c8FCMtdKYOuMJhzZ5qJXrQWtfb+EoDtLmM7Fv/0jZ4=,tag:rLmjQcyCD9mx8PQ2IjFOLA==,type:str]
        key: ""
    certSANs: []
    features:
        diskQuotaSupport: ENC[AES256_GCM,data:+S5OHg==,iv:SIVH23nhjbham4q31PLmal/GEkmgn3wz5fXWwPleGcg=,tag:Zrk+KEayp/+jTcF28VU0xg==,type:bool]
        hostDNS:
            enabled: ENC[AES256_GCM,data:euJVNg==,iv:IUcCbURtYkWmlfhRDBSJsrbsQcaBo9I22QaN8UFSDkU=,tag:rLq/a+6M0hmA3BCXQwWV8Q==,type:bool]
            forwardKubeDNSToHost: ENC[AES256_GCM,data:RlNX7A==,iv:QJnrMKxw+X5tHg6+m7hiGBWY69Jjwqe9KXYbAFE+0es=,tag:zqMJoE49rQDR/CxY7RYY/Q==,type:bool]
        kubePrism:
            enabled: ENC[AES256_GCM,data:y75y/Q==,iv:f+e1hff4QONBKbYkSZ426LidIOAJ9Bu/urhPreA9sqM=,tag:FDvN6EJJ9/+Yzh5Rq4WXaw==,type:bool]
            port: ENC[AES256_GCM,data:Hv9/RQ==,iv:VUlGQJa0Vj4qBjWnVh+GI52Q2Re6VQccrZo8X8dStUI=,tag:zL0AAFoPQQqrXSsQRsl9LQ==,type:int]
    install:
        disk: ENC[AES256_GCM,data:DvYiw1tNp9M=,iv:OnjwwLtFERhzu1mSJ8OZ8hTsnYRH2J6pVTEz0a1J6Gk=,tag:aaLutWVvPgH1rx/QcJW8TQ==,type:str]
        grubUseUKICmdline: ENC[AES256_GCM,data:lvsnwQ==,iv:vgh1Jk4ulTYtxyTbgRKeHO5Txi7KlLqRzY3JG3pIW6s=,tag:mhgBtqoUBDEAsSDqlxrneA==,type:bool]
        image: ENC[AES256_GCM,data:CJNRUdsNdzwgD7Nda6Cn7ZL2rveF/UyxKVxH6Nk00X0SoKX9,iv:6lX+wxfwktbq7hkGK0kid9uEQ4OTx97ZUkkqoLPaKJU=,tag:juoon2Nkuo2v5Ktul8F9HA==,type:str]
        wipe: ENC[AES256_GCM,data:NbIajUE=,iv:29JVZrO8Z++bkU4dXa/e/u+GG7E4sgPtS7G7FWLXmn8=,tag:mepIXfa6wM/NsOmJv5/4FQ==,type:bool]
    kubelet:
        defaultRuntimeSeccompProfileEnabled: ENC[AES256_GCM,data:GdGjeg==,iv:rTYM3yGUO1txF1DANbCZxeXlBwH6325QAeIfa4cmjp0=,tag:fbjtRnSy00OXNft+kCgmqg==,type:bool]
        disableManifestsDirectory: ENC[AES256_GCM,data:vZxQ5Q==,iv:KRIugRq6P/ku9Zg4MgY+ab77imJ52bGpNW96JEGOFBM=,tag:TVP/0zWCTYv0/p51/mPrZA==,type:bool]
        image: ENC[AES256_GCM,data:2L/moH1uJHPz8kZo3RHPP+yXqKd7R/mb6QZduI8DqcnMCg==,iv:TAGzn6ClZD3ARZscmXZRVjxYQ2JrnV2uCwjLxeTKMTc=,tag:u+XckzTAFn2FGwTLgmS7sQ==,type:str]
    network: {}
    registries: {}
    token: ENC[AES256_GCM,data:a+L4wXD8rA32q4gScws/L8zl9h6jH5A=,iv:bUlM6wxfjHTmW6wO4CSumCncBnkJa6DzO2We0ZqT6qM=,tag:TaSscaFM7W42cl21eqfecw==,type:str]
    type: ENC[AES256_GCM,data:IrADL3kg,iv:SfTyEkNkyPhjzEQB/YriHSd1C0uEpLTOqw3NeKhJ0/o=,tag:lV5nTLyBD8HLmfSECyOP8Q==,type:str]
persist: ENC[AES256_GCM,data:qHofDg==,iv:MUa4paaSEPLtjDBU0mP0ww/QleyIXGF2GX3kbIV8J98=,tag:S+FyJsQNKp5rCPQAKoHS6w==,type:bool]
version: ENC[AES256_GCM,data:rdZjPqM0YM8=,iv:rtoDfRK+GXo1QF4WYkDt+fUU+r90WhN3yWShZNKJCQc=,tag:5qzmIivCExwIzHJ4d+YGdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18nppsdntt6frwzus30c6n74fpgr6zwqvhampmr6m8qtzl64v857qg55kg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQVlHOEovQjRQSHBwVFRr
            ZVVHemFETnpoc3k0ZytYNGhQclFMZWE2SEI0CkRBaVJjVmY0S3h2QjNQM3RXajVM
            bldIREVFSmtiaGFUTmlpZU1wS082WDAKLS0tIGNUdEtmWk4zbnpLS0s5bHVTRDNa
            NHZaNG8ySStIaUpuVlltZ2haVHV1dVEKABJ8b3CJn574yRjRUkXeRHVygf/aJJXN
            wPo9ZLXv6ny8zydeU2gw3ACcH/TY0bzC4yTQpD++4d3rN3J6S5nm7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T01:35:46Z"
    mac: ENC[AES256_GCM,data:ifAyLUaAIBc9GMlGxB8rEOewqDbTkkc8/v1p9mjHzeZR/ci+tiUuizrhCGteOLqsjxDtt0hNVx8heOJaNAGvprKR6T+vxqUKnGpN/eh5YzpeG6ffxsqUDu9rma6k0yYA14zKYI/Ay/g6k33kQ7BD3SAoGPaHUJZIUfViTzfjKuM=,iv:IkgAyQUdJVS92VFRqViV3ozImNiSWuCn6pqg/Z9Ytvc=,tag:d/qGgOo7caPN6rJJISovYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
---
apiVersion: ENC[AES256_GCM,data:qqzOsgtHIpE=,iv:j27puqk8elD4pW2iB5pzEN+e8/rJIw3pNMTaP8NO2sc=,tag:5avI5F264+zQgLJmMF3zBA==,type:str]
auto: ENC[AES256_GCM,data:Hr0BMkaq,iv:hF7y0/1NP3qhytTggEhha1KR7ULbayRR2YprYfgwrN8=,tag:MmaivihCqKVl34xdONGWsA==,type:str]
kind: ENC[AES256_GCM,data:MM8ZhFe8Rmg/u986oFU=,iv:4hWcQUTREJJY0l72K2GCUUhe8Pi+bSYNR6a68j49/v8=,tag:NHI/0yODYmCkJZo/9VuvNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18nppsdntt6frwzus30c6n74fpgr6zwqvhampmr6m8qtzl64v857qg55kg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQVlHOEovQjRQSHBwVFRr
            ZVVHemFETnpoc3k0ZytYNGhQclFMZWE2SEI0CkRBaVJjVmY0S3h2QjNQM3RXajVM
            bldIREVFSmtiaGFUTmlpZU1wS082WDAKLS0tIGNUdEtmWk4zbnpLS0s5bHVTRDNa
            NHZaNG8ySStIaUpuVlltZ2haVHV1dVEKABJ8b3CJn574yRjRUkXeRHVygf/aJJXN
            wPo9ZLXv6ny8zydeU2gw3ACcH/TY0bzC4yTQpD++4d3rN3J6S5nm7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T01:35:46Z"
    mac: ENC[AES256_GCM,data:ifAyLUaAIBc9GMlGxB8rEOewqDbTkkc8/v1p9mjHzeZR/ci+tiUuizrhCGteOLqsjxDtt0hNVx8heOJaNAGvprKR6T+vxqUKnGpN/eh5YzpeG6ffxsqUDu9rma6k0yYA14zKYI/Ay/g6k33kQ7BD3SAoGPaHUJZIUfViTzfjKuM=,iv:IkgAyQUdJVS92VFRqViV3ozImNiSWuCn6pqg/Z9Ytvc=,tag:d/qGgOo7caPN6rJJISovYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
