apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: oznu/cloudflare-ddns:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-token
                  key: api-token
            - name: ZONE
              value: "tazlab.net"
            - name: PROXIED
              value: "false"
            - name: RRTYPE
              value: "A"
            - name: DELETE_ON_STOP
              value: "false"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi